import { Arrangement } from "../../pages/Map/components/blockMap/type";

export const DblockConfig: Arrangement = [
    [
        { type: "main" },
        { type: "main",  roadHash: new Set([194])},
        { type: "main", roadHash: new Set([193]) },
        { type: "main", roadHash: new Set([192]) },
        { type: "main", roadHash: new Set([192]) },
        { type: "main", roadHash: new Set([191]) },
        { type: "main", roadHash: new Set([190]) },
        { type: "main", roadHash: new Set([189]) },
        { type: "main", roadHash: new Set([188]) },
        { type: "main", roadHash: new Set([187]) },
        { type: "main", roadHash: new Set([187]) },
        { type: "main", roadHash: new Set([186]) },
        { type: "main", roadHash: new Set([185]) },
        { type: "main", roadHash: new Set([184]) },
        { type: "main", roadHash: new Set([183]) },
        { type: "main", roadHash: new Set([183]) },
        { type: "main", roadHash: new Set([182]) },
        { type: "main", roadHash: new Set([181]) },
        { type: "main", roadHash: new Set([180]) },
        { type: "main", roadHash: new Set([179]) },
        { type: "main", roadHash: new Set([178]) },
        { type: "main" },
    ],
    [
        { type: "main", rotn: "90deg"},
        { type: "residential", structureNo: "194" },
        { type: "residential", structureNo: "193" },
        { type: "residential", structureNo: "192" },
        { type: "residential" },
        { type: "residential", structureNo: "191" },
        { type: "residential", structureNo: "190" },
        { type: "gym", structureNo: "189" },
        { type: "residential", structureNo: "188" },
        { type: "residential", structureNo: "187" },
        { type: "residential" },
        { type: "residential", structureNo: "186" },
        { type: "residential", structureNo: "185" },
        { type: "residential", structureNo: "184" },
        { type: "residential", structureNo: "183" },
        { type: "residential" },
        { type: "residential", structureNo: "182" },
        { type: "residential", structureNo: "181"},
        { type: "residential", structureNo: "180" },
        { type: "residential", structureNo: "179" },
        { type: "residential", structureNo: "178" },
        { type: "service" },
    ],
    [
        { type: "main", rotn: "90deg" },
        { type: "residential", structureNo: "161" },
        { type: "residential", structureNo: "162" },
        { type: "residential", structureNo: "163" },
        { type: "residential", structureNo: "164" },
        { type: "gym", structureNo: "165" },
        { type: "residential", structureNo: "166" },
        { type: "residential", structureNo: "167" },
        { type: "residential", structureNo: "168" },
        { type: "residential", structureNo: "169" },
        { type: "residential", structureNo: "170" },
        { type: "residential"},
        { type: "residential", structureNo: "171" },
        { type: "residential", structureNo: "172" },
        { type: "residential", structureNo: "173" },
        { type: "residential" },
        { type: "residential", structureNo: "174" },
        { type: "residential", structureNo: "175" },
        { type: "residential", structureNo: "176"},
        { type: "gym", structureNo: "177" },
        { type: "residential" },
        { type: "service"},
    ],
    [
        { type: "main", rotn: "90deg" },
        { type: "service", roadHash: new Set([161, 160])},
        { type: "service", roadHash: new Set([162]) },
        { type: "service", roadHash: new Set([163]) },
        { type: "service", roadHash: new Set([164, 121]) },
        { type: "service", roadHash: new Set([165]) },
        { type: "service", roadHash: new Set([166, 120]) },
        { type: "service", roadHash: new Set([167, 119]) },
        { type: "service", roadHash: new Set([168, 118]) },
        { type: "service", roadHash: new Set([169, 117]) },
        { type: "service", roadHash: new Set([170, 116]) },
        { type: "service", roadHash: new Set([170, 115]) },
        { type: "service", roadHash: new Set([171, 114]) },
        { type: "service", roadHash: new Set([172, 113]) },
        { type: "service", roadHash: new Set([173, 112]) },
        { type: "service", roadHash: new Set([173, 111]) },
        { type: "service", roadHash: new Set([174, 110]) },
        { type: "service", roadHash: new Set([175, 109]) },
        { type: "service", roadHash: new Set([176, 108]) },
        { type: "service" },
        { type: "service", roadHash: new Set([177, 107]) },
        { type: "service" },
    ],
    [
        { type: "main",roadHash: new Set([160]) , rotn: "90deg" },
        { type: "residential", structureNo: "160" },
        { type: "residential" },
        { type: "residential", structureNo: "121" },
        { type: "residential" },
        { type: "service", roadHash: new Set([121]) },
        { type: "residential", structureNo: "120" },
        { type: "residential", structureNo: "119" },
        { type: "residential", structureNo: "118" },
        { type: "residential", structureNo: "117" },
        { type: "residential", structureNo: "116" },
        { type: "rent", structureNo: "115" },
        { type: "residential", structureNo: "114" },
        { type: "residential", structureNo: "113" },
        { type: "residential", structureNo: "112" },
        { type: "residential", structureNo: "111" },
        { type: "residential", structureNo: "110" },
        { type: "pg", structureNo: "109" },
        { type: "residential", structureNo: "108" },
        { type: "rent", structureNo: "107"},
        { type: "residential" },
        { type: "service" },
    ],
    [   
        { type: "main",roadHash: new Set([159]), rotn: "90deg" },
        { type: "residential", structureNo: "159" },
        { type: "residential" },     
        { type: "residential", structureNo: "122" },
        { type: "residential"},
        { type: "service", roadHash: new Set([122]) },
        { type: "residential", structureNo: "120" },
        { type: "residential", structureNo: "119" },
        { type: "residential", structureNo: "118" },
        { type: "residential", structureNo: "117" },
        { type: "residential", structureNo: "116" },
        { type: "residential", structureNo: "115"},
        { type: "residential", structureNo: "114" },
        { type: "residential", structureNo: "113" },
        { type: "residential", structureNo: "112" },
        { type: "residential", structureNo: "111" },
        { type: "residential", structureNo: "110" },
        { type: "residential", structureNo: "109" },
        { type: "residential", structureNo: "108" },
        { type: "residential", structureNo: "107"},
        { type: "residential" },
        { type: "service" },
    ],
    [
        { type: "main", roadHash: new Set([158]), rotn: "90deg" },
        { type: "residential",structureNo: "158" },
        { type: "residential" },
        { type: "residential", structureNo: "123"},
        { type: "residential" },
        { type: "service", roadHash: new Set([123]) },
        { type: "residential", structureNo: "92" },
        { type: "residential", structureNo: "93" },
        { type: "residential" },
        { type: "rent", structureNo: "94" },
        { type: "residential", structureNo: "95" },
        { type: "residential", structureNo: "96" },
        { type: "residential", structureNo: "97" },
        { type: "residential", structureNo: "98" },
        { type: "residential", structureNo: "99" },
        { type: "residential", structureNo: "100" },
        { type: "residential", structureNo: "101" },
        { type: "rent", structureNo: "102" },
        { type: "residential", structureNo: "103" },
        { type: "residential", structureNo: "104" },
        { type: "residential", structureNo: "105" },
        { type: "service", roadHash: new Set([105]) },
    ],
    [
        { type: "main",roadHash: new Set([157]), rotn: "90deg" },
        { type: "residential",structureNo: "157" },
        { type: "residential" },
        { type: "residential", structureNo: "124" },
        { type: "residential" },
        { type: "service", roadHash: new Set([124]) },
        { type: "service", roadHash: new Set([92])},
        { type: "service", roadHash: new Set([93]) },
        { type: "service" },
        { type: "service", roadHash: new Set([94]) },
        { type: "service", roadHash: new Set([95]) },
        { type: "service", roadHash: new Set([96]) },
        { type: "service", roadHash: new Set([97]) },
        { type: "service", roadHash: new Set([98]) },
        { type: "service", roadHash: new Set([99]) },
        { type: "service", roadHash: new Set([100]) },
        { type: "service", roadHash: new Set([101]) },
        { type: "service", roadHash: new Set([102]) },
        { type: "service", roadHash: new Set([103]) },
        { type: "service", roadHash: new Set([104]) },
        { type: "service", roadHash: new Set([105]) },
        { type: "service" },
    ],
    [
        { type: "main", roadHash: new Set([156]), rotn: "90deg" },
        { type: "residential", structureNo : "156" },
        { type: "residential" },
        { type: "residential", structureNo: "125" },
        { type: "residential" },
        { type: "service", roadHash: new Set([125, 90]) },
        { type: "residential", structureNo: "90" },
        { type: "residential" },
        { type: "residential" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([66]) },
        { type: "residential", structureNo: "66" },
        { type: "rent" },
        { type: "residential", structureNo: "65" },
        { type: "residential" },
        { type: "service", roadHash: new Set([65]) },
    ],
    [
        { type: "main",roadHash: new Set([155]), rotn: "90deg" },
        { type: "residential", structureNo: "155"},
        { type: "residential" },
        { type: "residential", structureNo: "126"},
        { type: "residential" },
        { type: "service", roadHash: new Set([126, 89]) },
        { type: "residential", structureNo: "89" },
        { type: "residential" },
        { type: "residential" },
        { type: "park"},
        { type: "park"},
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park"},
        { type: "park" },
        { type: "service" },
        { type: "residential", structureNo: "67" },
        { type: "residential" },
        { type: "residential", structureNo: "64" },
        { type: "residential" },
        { type: "service", roadHash: new Set([64]) },
    ],
    [
        { type: "main",roadHash: new Set([154]), rotn: "90deg" },
        { type: "residential", structureNo:"154"},
        { type: "residential"},
        { type: "residential", structureNo: "127" },
        { type: "residential" },
        { type: "service", roadHash: new Set([127, 88]) },
        { type: "residential", structureNo: "88"},
        { type: "residential" },
        { type: "residential" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([68]) },
        { type: "residential", structureNo: "68"},
        { type: "residential", structureNo: "68" },
        { type: "residential", structureNo: "63"},
        { type: "residential", structureNo: "63" },
        { type: "service", roadHash: new Set([63]) },
    ],
    [
        { type: "main",roadHash: new Set([153]), rotn: "90deg" },
        { type: "residential", structureNo: "153" },
        { type: "residential", structureNo: "153" },
        { type: "residential", structureNo: "128"},
        { type: "residential", structureNo: "128" },
        { type: "service",roadHash: new Set([128, 87]) },
        { type: "residential", structureNo: "87" },
        { type: "residential", structureNo: "87" },
        { type: "residential", structureNo: "87" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([69]) },
        { type: "residential", structureNo: "69" }, { type: "residential", structureNo: "69" },
        { type: "residential", structureNo: "62" },
        { type: "residential", structureNo: "62" },
        { type: "service", roadHash: new Set([62]) },
    ],
    [
        { type: "main",roadHash: new Set([152]), rotn: "90deg" },
        { type: "residential", structureNo: "152" },
        { type: "residential", structureNo: "152" },
        { type: "residential", structureNo: "129" },
        { type: "residential", structureNo: "129" },
        { type: "service", roadHash: new Set([129, 86]) },
        { type: "residential", structureNo: "86"},
        { type: "residential", structureNo: "86" },
        { type: "residential", structureNo: "86" },
        { type: "park"},
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([70]) },
        { type: "residential", structureNo: "70" },
        { type: "residential", structureNo: "70" },
        { type: "residential", structureNo: "61" },
        { type: "residential", structureNo: "61" },
        { type: "service", roadHash: new Set([61]) },
    ],
    [
        { type: "main",roadHash: new Set([151]), rotn: "90deg" },
        { type: "residential", structureNo: "151" },
        { type: "residential", structureNo: "151" },
        { type: "residential", structureNo: "130" },
        { type: "residential", structureNo: "130" },
        { type: "service", roadHash: new Set([130, 85]) },
        { type: "residential", structureNo: "85"},
        { type: "residential", structureNo: "85" },
        { type: "residential", structureNo: "85" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([71]) },
        { type: "residential", structureNo: "71"},
        { type: "residential", structureNo: "71" },
        { type: "residential", structureNo: "60" },
        { type: "residential", structureNo: "60" },
        { type: "service", roadHash: new Set([60]) },
    ],
    [
        { type: "main",roadHash: new Set([150]), rotn: "90deg" },
        { type: "residential", structureNo:"150" },
        { type: "residential", structureNo: "150" },
        { type: "residential", structureNo: "131" },
        { type: "residential", structureNo: "131" },
        { type: "service", roadHash: new Set([131, 84]) },
        { type: "residential", structureNo: "84" },
        { type: "residential", structureNo: "84" },
        { type: "residential", structureNo: "84" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([72]) },
        { type: "residential", structureNo: "72" },
        { type: "residential", structureNo: "72" },
        { type: "residential",structureNo: "59" },
        { type: "residential", structureNo: "59" },
        { type: "service", roadHash: new Set([59]) },
    ],
    [
        { type: "main",roadHash: new Set([149]), rotn: "90deg" },
        { type: "residential", structureNo: "149" }, { type: "residential", structureNo: "149" },
        { type: "residential", structureNo: "132" },
        { type: "residential", structureNo: "132" },
        { type: "service", roadHash: new Set([132, 83]) },
        { type: "residential", structureNo: "83"},
        { type: "residential", structureNo: "83" },
        { type: "residential", structureNo: "83" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([73]) },
        { type: "residential", structureNo: "73" },
        { type: "residential", structureNo: "73" },
        { type: "residential", structureNo: "58" },
        { type: "residential", structureNo: "58" },
        { type: "service", roadHash: new Set([58]) },
    ],
    [
        { type: "main",roadHash: new Set([148]), rotn: "90deg" },
        { type: "residential", structureNo:"148" },
        { type: "residential", structureNo: "148" },
        { type: "residential", structureNo: "133" },
        { type: "residential", structureNo: "133" },
        { type: "service", roadHash: new Set([133, 82]) },
        { type: "residential", structureNo: "82" },
        { type: "residential"},
        { type: "residential", structureNo: "82" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([74]) },
        { type: "residential", structureNo: "74" },
        { type: "residential", structureNo: "74" },
        { type: "residential",structureNo: "57"},
        { type: "residential", structureNo: "57" },
        { type: "service", roadHash:new Set([57]) },
    ],
    [
        { type: "main", roadHash: new Set([147]) },
        { type: "residential", structureNo:"147"},
        { type: "residential", structureNo: "147" },
        { type: "residential", structureNo: "134" },
        { type: "residential", structureNo: "134" },
        { type: "service", roadHash: new Set([134, 81]) },
        { type: "residential", structureNo: "81" },
        { type: "residential" },
        { type: "residential", structureNo: "81" },
        { type: "park"},
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([75]) },
        { type: "residential", structureNo: "75" },
        { type: "residential", structureNo: "75" },
        { type: "residential", structureNo:"56"},
        { type: "residential", structureNo: "56" },
        { type: "service", roadHash: new Set([56]) },
    ],
    [
        { type: "main", roadHash: new Set([146]) },
        { type: "residential", structureNo:"146"},
        { type: "residential", structureNo: "146" },
        { type: "residential", structureNo: "135"},
        { type: "residential", structureNo: "135" },
        { type: "service", roadHash: new Set([135, 80]) },
        { type: "residential", structureNo: "80" },
        { type: "residential" },
        { type: "residential", structureNo: "80" },
        { type: "park"},
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "park" },
        { type: "service", roadHash: new Set([76]) },
        { type: "residential", structureNo: "76" },
        { type: "residential", structureNo: "76" },
        { type: "residential", structureNo:"54" },
        { type: "residential", structureNo: "54" },
        { type: "service", roadHash: new Set([54]) },
    ],
    [
        { type: "main", roadHash: new Set([145]) },
        { type: "residential", structureNo:"145"},
        { type: "residential", structureNo: "145" },
        { type: "residential", structureNo: "136" },
        { type: "residential", structureNo: "136" },
        { type: "service", roadHash: new Set([136]) },
        { type: "service", roadHash: new Set([80, 37]) },
        { type: "service", roadHash: new Set([80, 38]) },
        { type: "service", roadHash: new Set([39]) },
        { type: "service", roadHash: new Set([40]) },
        { type: "service", roadHash: new Set([41]) },
        { type: "service", roadHash: new Set([42]) },
        { type: "service", roadHash: new Set([43]) },
        { type: "service", roadHash: new Set([44]) },
        { type: "service", roadHash: new Set([45]) },
        { type: "service", roadHash: new Set([46]) },
        { type: "service", roadHash: new Set([47]) },
        { type: "service", roadHash: new Set([48, 76]) },
        { type: "service", roadHash: new Set([49]) },
        { type: "service", roadHash: new Set([50]) },
        { type: "service", roadHash: new Set([51, 54]) },
        { type: "service" },
    ],
    [
        { type: "main", roadHash: new Set([144]) },
        { type: "residential", structureNo:"144" },
        { type: "residential", structureNo: "144" },
        {type: "residential", structureNo: "137"},
        { type: "residential", structureNo: "137" },
        {type: "service", roadHash: new Set([137, 37])},
        { type: "residential", structureNo: "37" },
        { type: "residential", structureNo: "38" },
        { type: "residential", structureNo: "39" },
        { type: "residential", structureNo: "40" },
        { type: "residential", structureNo: "41" },
        { type: "medical", structureNo: "42" },
        { type: "residential", structureNo: "43" },
        { type: "residential", structureNo: "44" },
        { type: "residential", structureNo: "45" },
        { type: "residential", structureNo: "46" },
        { type: "residential", structureNo: "47" },
        { type: "residential", structureNo: "48" },
        { type: "residential", structureNo: "49" },
        { type: "residential", structureNo: "50" },
        { type: "pg", structureNo: "51" },
        { type: "service" },
    ],
    [
        { type: "main", roadHash: new Set([143])},
        { type: "residential", structureNo:"143"},
        { type: "residential", structureNo: "143" },
        { type: "residential", structureNo: "138"},
        { type: "residential", structureNo: "138" },
        { type:"service", roadHash: new Set([138]) },
        { type: "residential", structureNo: "37" },
        { type: "residential", structureNo: "38" },
        { type: "residential", structureNo: "39" },
        { type: "residential", structureNo: "40" },
        { type: "residential", structureNo: "41" },
        { type: "residential", structureNo: "42" },
        { type: "medical", structureNo: "43" },
        { type: "residential", structureNo: "44" },
        { type: "residential", structureNo: "45" },
        { type: "residential", structureNo: "46" },
        { type: "residential", structureNo: "47" },
        { type: "residential", structureNo: "48" },
        { type: "residential", structureNo: "49" },
        { type: "residential", structureNo: "50" },
        { type: "pg", structureNo: "51" },
        { type: "service" },
    ],
    [
        { type: "main", roadHash: new Set([142]) },
        { type: "residential", structureNo:"142"},
        { type: "residential", structureNo: "142" },
        { type: "residential", structureNo: "139" },
        { type: "residential", structureNo: "139" },
        { type: "service", roadHash: new Set([139]) },
        { type: "residential", structureNo: "36" },
        { type: "residential", structureNo: "35" },
        { type: "residential", structureNo: "34" },
        { type: "residential", structureNo: "33" },
        { type: "residential", structureNo: "32" },
        { type: "residential", structureNo: "31" },
        { type: "residential", structureNo: "30" },
        { type: "residential", structureNo: "29" },
        { type: "residential", structureNo: "28" },
        { type: "residential", structureNo: "27" },
        { type: "residential", structureNo: "26" },
        { type: "residential", structureNo: "25" },
        { type: "pg", structureNo: "24" },
        { type: "residential", structureNo: "23" },
        { type: "residential", structureNo: "22" },
        { type: "service" },
    ],
    [
        { type: "main", roadHash: new Set([141]) },
        { type: "residential", structureNo: "141" },
        { type: "residential", structureNo: "141" },
        { type: "residential", structureNo: "140"},
        { type: "residential", structureNo: "140" },
        { type: "service", roadHash: new Set([140, 36]) },
        { type: "residential", structureNo: "36" },
        { type: "residential", structureNo: "35" },
        { type: "residential", structureNo: "34" },
        { type: "residential", structureNo: "33" },
        { type: "residential", structureNo: "32" },
        { type: "pg", structureNo: "31" },
        { type: "residential", structureNo: "30" },
        { type: "residential", structureNo: "29" },
        { type: "residential", structureNo: "28" },
        { type: "residential", structureNo: "27" },
        { type: "pg", structureNo: "26" },
        { type: "residential", structureNo: "25" },
        { type: "residential", structureNo: "24" },
        { type: "residential", structureNo: "23" },
        { type: "residential", structureNo: "22" },
        { type: "service" },
    ],
    [
        { type: "main" },
        { type: "service" },
        { type: "service" },
        { type: "service" },
        { type: "service" },
        { type: "service" },
        { type: "service", roadHash: new Set([36, 10]) },
        { type: "service", roadHash: new Set([35, 10]) },
        { type: "service", roadHash: new Set([34, 11]) },
        { type: "service", roadHash: new Set([33, 12]) },
        { type: "service", roadHash: new Set([32, 13]) },
        { type: "service", roadHash: new Set([31, 14]) },
        { type: "service", roadHash: new Set([30, 15]) },
        { type: "service", roadHash: new Set([29, 16]) },
        { type: "service", roadHash: new Set([28, 16]) },
        { type: "service", roadHash: new Set([27, 17]) },
        { type: "service", roadHash: new Set([26, 18]) },
        { type: "service", roadHash: new Set([25, 19]) },
        { type: "service", roadHash: new Set([24, 20]) },
        { type: "service", roadHash: new Set([23, 20]) },
        { type: "service", roadHash: new Set([22, 21]) },
        { type: "service" },
    ],
    [
        { type: "main" },
        {type: "commercial"},
        {type: "commercial"},
        {type: "commercial"},
        { type: "commercial" },
        { type: "commercial" },
        {type:"residential", structureNo:"10"},
        { type: "residential", structureNo: "10" },
        { type: "residential", structureNo: "11" },
        { type: "residential", structureNo: "12" },
        { type: "residential", structureNo: "13" },
        { type: "pg", structureNo: "14" },
        { type: "residential", structureNo: "15" },
        { type: "residential", structureNo: "16" },
        { type: "residential", structureNo: "16" },
        { type: "residential", structureNo: "17" },
        { type: "residential", structureNo: "18" },
        { type: "residential", structureNo: "19" },
        { type: "residential", structureNo: "20" },
        { type: "residential", structureNo: "20" },
        { type: "residential", structureNo: "21" },
        { type: "service"},
    ],
    [
        { type: "main" },
        { type: "commercial" },
        { type: "commercial" },
        { type: "commercial" },
        { type: "commercial" },
        { type: "commercial" },
        { type: "residential", structureNo: "1" },
        { type: "residential", structureNo: "1" },
        { type: "residential", structureNo: "2" },
        { type: "residential", structureNo: "3" },
        { type: "residential", structureNo: "3" },
        { type: "residential", structureNo: "4"},
        { type: "residential", structureNo: "5" },
        { type: "residential", structureNo: "6" },
        { type: "residential", structureNo: "6" },
        { type: "residential", structureNo: "7" },
        { type: "residential", structureNo: "8" },
        { type: "residential", structureNo: "8" },
        { type: "residential", structureNo: "8" },
        { type: "residential", structureNo: "9" },
        { type: "residential", structureNo: "9" },
        { type: "service" },   
    ],
    [
        { type: "main" },
        { type: "main" },
        { type: "main" },
        { type: "main" },
        { type: "main" },
        { type: "main" },
        { type: "main", roadHash: new Set([1]) },
        { type: "main", roadHash: new Set([1]) },
        { type: "main", roadHash: new Set([2]) },
        { type: "main", roadHash: new Set([3]) },
        { type: "main", roadHash: new Set([3]) },
        { type: "main", roadHash: new Set([4]) },
        { type: "main", roadHash: new Set([5]) },
        { type: "main", roadHash: new Set([6]) },
        { type: "main", roadHash: new Set([6]) },
        { type: "main", roadHash: new Set([7]) },
        { type: "main", roadHash: new Set([8]) },
        { type: "main", roadHash: new Set([8]) },
        { type: "main", roadHash: new Set([8]) },
        { type: "main", roadHash: new Set([9]) },
        { type: "main", roadHash: new Set([9]) },
        { type: "main" },
    ],
]